//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossfitbook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CfBookModelContainer : DbContext
    {
        public CfBookModelContainer()
            : base("name=CfBookModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> ClubSet { get; set; }
        public virtual DbSet<ClubWorkTime> ClubWorkTimeSet { get; set; }
        public virtual DbSet<Equipment> EquipmentSet { get; set; }
        public virtual DbSet<Manufacturer> ManufacturerSet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<City> CitySet { get; set; }
        public virtual DbSet<SocialNetwork> SocialNetworkSet { get; set; }
        public virtual DbSet<Wod> WodSet { get; set; }
        public virtual DbSet<Exercise> ExerciseSet { get; set; }
        public virtual DbSet<ExerciseType> ExerciseTypeSet { get; set; }
        public virtual DbSet<Image> ImageSet { get; set; }
        public virtual DbSet<LoadType> LoadTypeSet { get; set; }
        public virtual DbSet<ClubNetwork> ClubNetworkSet { get; set; }
        public virtual DbSet<WodCategory> WodCategorySet { get; set; }
        public virtual DbSet<News> NewsSet { get; set; }
        public virtual DbSet<NewsType> NewsTypeSet { get; set; }
    }
}
