//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossfitbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.City = new HashSet<City>();
            this.SocialNetwork = new HashSet<SocialNetwork>();
            this.Equipment = new HashSet<Equipment>();
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string WebPage { get; set; }
        public int MaxPeopleCount { get; set; }
        public Nullable<bool> IsSwimmingPool { get; set; }
        public bool IsSauna { get; set; }
        public double CellingHeight { get; set; }
        public double XCoordinate { get; set; }
        public double YCoordinate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialNetwork> SocialNetwork { get; set; }
        public virtual ClubNetwork ClubNetwork { get; set; }
        public virtual ClubWorkTime ClubWorkTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
    }
}
