//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossfitbook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wod()
        {
            this.Exercise = new HashSet<Exercise>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Rounds { get; set; }
        public string Task { get; set; }
        public string Rating { get; set; }
    
        public virtual LoadType LoadType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise> Exercise { get; set; }
        public virtual WodCategory WodCategory { get; set; }
    }
}
